name: harukashogi
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.2
  - aom=3.9.1
  - attr=2.5.2
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cpython=3.13.11
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - dav1d=1.2.1
  - dbus=1.16.2
  - filelock=3.20.2
  - fluidsynth=2.5.2
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fsspec=2025.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=78.2
  - jack=1.9.22
  - jinja2=3.1.6
  - lame=3.100
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcudss=0.7.1.4
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.25
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmad=0.15.1b
  - libmagma=2.9.0
  - libmpdec=4.0.0
  - libnl=3.11.0
  - libnvjitlink=12.9.86
  - libogg=1.3.5
  - libopus=1.6
  - libpciaccess=0.18
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - libsndfile=1.2.2
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libtorch=2.9.1
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libuuid=2.41.3
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - nccl=2.29.2.1
  - ncurses=6.5
  - networkx=3.6.1
  - numpy=2.4.0
  - openssl=3.6.0
  - optree=0.18.0
  - opusfile=0.12
  - pcre2=10.47
  - pip=25.3
  - pixman=0.46.4
  - portaudio=19.7.0
  - portmidi=2.0.8
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pygame=2.6.1
  - pyinstrument=5.1.2
  - python=3.13.11
  - python_abi=3.13
  - pytorch=2.9.1
  - rav1e=0.7.1
  - rdma-core=60.0
  - readline=8.3
  - sdl2=2.32.56
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.24.0
  - sdl3=3.2.30
  - setuptools=80.9.0
  - sleef=3.9.0
  - snakeviz=2.2.2
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - tornado=6.5.4
  - triton=3.5.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wayland=1.24.0
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - zstd=1.5.7

prefix: "/home/fausto/miniforge3/envs/harukashogi"
